### Load in NumPy (remember to pip install numpy first)

In [303]:
import numpy as np

### The Basics

In [304]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [305]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [306]:
# Get Dimension
a.ndim

1

In [307]:
# Get Shape
b.shape

(2, 3)

In [308]:
# Get Type
a.dtype

dtype('int32')

In [309]:
# Get Size (Byte , int32 is 4 byte)
a.itemsize

4

In [310]:
# Get total size(a.size * a.itemsize)
a.nbytes

12

In [311]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [312]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [313]:
# Get a specific element [r, c]
a[1, 5]

13

In [314]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [315]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [316]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [317]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [318]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [319]:
# Get specific element (work outside in)
b[0,1,1]

4

In [320]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [321]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [322]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [323]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [324]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [325]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [326]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.39231013, 0.93707762],
       [0.64097672, 0.08926505],
       [0.93104186, 0.42972526],
       [0.97444553, 0.37568727]])

In [327]:
# Random sample
np.random.random_sample(a.shape)

array([[0.47395243, 0.08988751, 0.56443023, 0.18677129, 0.16971623,
        0.50779311, 0.52039764],
       [0.864823  , 0.35424735, 0.35358868, 0.89133787, 0.63031022,
        0.6387942 , 0.87875076]])

In [328]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-3, -2,  4],
       [ 2,  7,  5],
       [ 3,  6, -1]])

In [329]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [330]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [331]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [332]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [333]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [334]:
a + 2

array([3, 4, 5, 6])

In [335]:
a - 2

array([-1,  0,  1,  2])

In [336]:
a * 2

array([2, 4, 6, 8])

In [337]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [338]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [339]:
a ** 2

array([ 1,  4,  9, 16])

In [340]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [341]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [342]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [343]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [344]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [345]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [346]:
np.min(stats)

1

In [347]:
np.max(stats, axis=1)

array([3, 6])

In [348]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [349]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [350]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [351]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [352]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [353]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [354]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [355]:
# You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
np.any(filedata > 50, axis=0)

In [356]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])